const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Behaviors.Pin,
		C3.Plugins.TiledBg,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Physics,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Behaviors.Anchor,
		C3.Plugins.Keyboard,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Browser,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Behaviors.Physics.Acts.SetAngularVelocity,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Behaviors.Physics.Acts.EnableCollisions,
		C3.Behaviors.Physics.Acts.CreateRevoluteJoint,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Behaviors.Pin.Acts.Unpin,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Browser.Acts.GoBack,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Browser.Cnds.IsPortraitLandscape,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.PlatformInfo.Cnds.IsOnAndroid,
		C3.Plugins.Browser.Acts.GoToURLWindow
	];
};
self.C3_JsPropNameTable = [
	{Синусоида: 0},
	{coin: 0},
	{decor: 0},
	{Прикрепить: 0},
	{fara_1: 0},
	{fara_2: 0},
	{finis: 0},
	{fonar: 0},
	{fonar2: 0},
	{fonar_L: 0},
	{fonar_R: 0},
	{gorod: 0},
	{kartinki: 0},
	{ДвижениеК: 0},
	{Физика: 0},
	{kovs: 0},
	{kran: 0},
	{leverLeft: 0},
	{mysirka2: 0},
	{mysor: 0},
	{nebo: 0},
	{pesok: 0},
	{podem: 0},
	{СледитьЗа: 0},
	{ОграничитьСценой: 0},
	{RedCar: 0},
	{stop: 0},
	{stop2: 0},
	{stop3: 0},
	{svetofor: 0},
	{svetofor2: 0},
	{Th1: 0},
	{Th2: 0},
	{triger_1: 0},
	{triger_2: 0},
	{triger_3: 0},
	{triger_ecs_OFF: 0},
	{triger_ecs_ON: 0},
	{vend: 0},
	{vend2: 0},
	{Wheel: 0},
	{Wheel2: 0},
	{zagr: 0},
	{ze: 0},
	{zemla: 0},
	{znak: 0},
	{triger_0: 0},
	{fonMenu: 0},
	{fonNazalo: 0},
	{Igrat_menu: 0},
	{kak_igrat_ins: 0},
	{kakIgrat: 0},
	{naYroven: 0},
	{Якорь: 0},
	{nazad: 0},
	{predyprezdenie: 0},
	{raz: 0},
	{restart: 0},
	{sver: 0},
	{vakl: 0},
	{vixod: 0},
	{vkl: 0},
	{vmenu: 0},
	{vpered: 0},
	{klava: 0},
	{tash: 0},
	{audio: 0},
	{obYsroistve: 0},
	{brauzer: 0},
	{blok: 0},
	{kod: 0},
	{speed: 0},
	{speed2: 0},
	{zvyk: 0},
	{zekran: 0},
	{demo: 0}
];

self.InstanceType = {
	coin: class extends self.ISpriteInstance {},
	decor: class extends self.ISpriteInstance {},
	fara_1: class extends self.ISpriteInstance {},
	fara_2: class extends self.ISpriteInstance {},
	finis: class extends self.ISpriteInstance {},
	fonar: class extends self.ISpriteInstance {},
	fonar2: class extends self.ISpriteInstance {},
	fonar_L: class extends self.ISpriteInstance {},
	fonar_R: class extends self.ISpriteInstance {},
	gorod: class extends self.ITiledBackgroundInstance {},
	kartinki: class extends self.ISpriteInstance {},
	kovs: class extends self.ISpriteInstance {},
	kran: class extends self.ISpriteInstance {},
	leverLeft: class extends self.ISpriteInstance {},
	mysirka2: class extends self.ISpriteInstance {},
	mysor: class extends self.ISpriteInstance {},
	nebo: class extends self.ITiledBackgroundInstance {},
	pesok: class extends self.ISpriteInstance {},
	podem: class extends self.ITiledBackgroundInstance {},
	RedCar: class extends self.ISpriteInstance {},
	stop: class extends self.ISpriteInstance {},
	stop2: class extends self.ISpriteInstance {},
	stop3: class extends self.ISpriteInstance {},
	svetofor: class extends self.ISpriteInstance {},
	svetofor2: class extends self.ISpriteInstance {},
	Th1: class extends self.ISpriteInstance {},
	Th2: class extends self.ISpriteInstance {},
	triger_1: class extends self.ISpriteInstance {},
	triger_2: class extends self.ISpriteInstance {},
	triger_3: class extends self.ISpriteInstance {},
	triger_ecs_OFF: class extends self.ISpriteInstance {},
	triger_ecs_ON: class extends self.ISpriteInstance {},
	vend: class extends self.ISpriteInstance {},
	vend2: class extends self.ISpriteInstance {},
	Wheel: class extends self.ISpriteInstance {},
	Wheel2: class extends self.ISpriteInstance {},
	zagr: class extends self.ISpriteInstance {},
	ze: class extends self.ISpriteInstance {},
	zemla: class extends self.ITiledBackgroundInstance {},
	znak: class extends self.ISpriteInstance {},
	triger_0: class extends self.ISpriteInstance {},
	fonMenu: class extends self.ISpriteInstance {},
	fonNazalo: class extends self.ISpriteInstance {},
	Igrat_menu: class extends self.ISpriteInstance {},
	kak_igrat_ins: class extends self.ISpriteInstance {},
	kakIgrat: class extends self.ISpriteInstance {},
	naYroven: class extends self.ISpriteInstance {},
	nazad: class extends self.ISpriteInstance {},
	predyprezdenie: class extends self.ISpriteInstance {},
	raz: class extends self.ISpriteInstance {},
	restart: class extends self.ISpriteInstance {},
	sver: class extends self.ISpriteInstance {},
	vakl: class extends self.ISpriteInstance {},
	vixod: class extends self.ISpriteInstance {},
	vkl: class extends self.ISpriteInstance {},
	vmenu: class extends self.ISpriteInstance {},
	vpered: class extends self.ISpriteInstance {},
	klava: class extends self.IInstance {},
	tash: class extends self.IInstance {},
	audio: class extends self.IInstance {},
	obYsroistve: class extends self.IInstance {},
	brauzer: class extends self.IInstance {},
	blok: class extends self.ISpriteInstance {},
	kod: class extends self.ISpriteInstance {}
}