const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.AdvancedRandom,
		C3.Plugins.Arr,
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Plugins.PlatformInfo,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.AdvancedRandom.Acts.CreatePermutationTable,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.AdvancedRandom.Exps.Permutation,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Browser.Acts.GoBack,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.PlatformInfo.Cnds.IsOnAndroid,
		C3.Plugins.Browser.Cnds.IsPortraitLandscape,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.CreateObject
	];
};
self.C3_JsPropNameTable = [
	{AdvancedRandom: 0},
	{CardsRandomizer: 0},
	{ur1: 0},
	{ur2: 0},
	{ur3: 0},
	{fonM: 0},
	{vMenu: 0},
	{vixod: 0},
	{v_menu: 0},
	{raz: 0},
	{sver: 0},
	{ID: 0},
	{Terbuka: 0},
	{beh_tween: 0},
	{Card: 0},
	{Touch: 0},
	{Browser: 0},
	{audio: 0},
	{zvezda: 0},
	{obYsroistve: 0},
	{predyprezdenie: 0},
	{vkl: 0},
	{vakl: 0},
	{kod: 0},
	{kod2: 0},
	{fon2: 0},
	{fon3: 0},
	{zvyki: 0},
	{Твинанимация: 0},
	{miska: 0},
	{prosto_logoped: 0},
	{kartuPertamaTerisi: 0},
	{kartu1: 0},
	{kartu2: 0},
	{Benar: 0},
	{Suara: 0},
	{zekran: 0},
	{pobeda: 0},
	{zvyk: 0},
	{demo: 0},
	{demo2: 0}
];

self.InstanceType = {
	AdvancedRandom: class extends self.IInstance {},
	CardsRandomizer: class extends self.IArrayInstance {},
	ur1: class extends self.ISpriteInstance {},
	ur2: class extends self.ISpriteInstance {},
	ur3: class extends self.ISpriteInstance {},
	fonM: class extends self.ISpriteInstance {},
	vMenu: class extends self.ISpriteInstance {},
	vixod: class extends self.ISpriteInstance {},
	v_menu: class extends self.ISpriteInstance {},
	raz: class extends self.ISpriteInstance {},
	sver: class extends self.ISpriteInstance {},
	Card: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	audio: class extends self.IInstance {},
	zvezda: class extends self.ISpriteInstance {},
	obYsroistve: class extends self.IInstance {},
	predyprezdenie: class extends self.ISpriteInstance {},
	vkl: class extends self.ISpriteInstance {},
	vakl: class extends self.ISpriteInstance {},
	kod: class extends self.ISpriteInstance {},
	kod2: class extends self.ISpriteInstance {},
	fon2: class extends self.ISpriteInstance {},
	fon3: class extends self.ISpriteInstance {},
	zvyki: class extends self.ISpriteInstance {},
	miska: class extends self.ISpriteInstance {},
	prosto_logoped: class extends self.ISpriteInstance {}
}