const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Browser,
		C3.Plugins.Keyboard,
		C3.Behaviors.Rotate,
		C3.Plugins.AJAX,
		C3.Plugins.Json,
		C3.Behaviors.Tween,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.System.Cnds.OnSignal,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Browser.Acts.GoBack,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Browser.Cnds.IsPortraitLandscape,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.PlatformInfo.Cnds.IsOnAndroid,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Cnds.CompareFrameTag,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.System.Acts.Signal,
		C3.Plugins.AJAX.Exps.Tag,
		C3.Plugins.AJAX.Cnds.OnAnyComplete,
		C3.Plugins.AJAX.Cnds.OnAnyError
	];
};
self.C3_JsPropNameTable = [
	{vakl: 0},
	{vixod: 0},
	{vkl: 0},
	{vMenu: 0},
	{kak_igrat: 0},
	{naMenu: 0},
	{naYroven_1: 0},
	{predyprezdenie: 0},
	{raz: 0},
	{restrt: 0},
	{sver: 0},
	{fon_kakigrat: 0},
	{fon_menu: 0},
	{Touch: 0},
	{audio: 0},
	{obYsroistve: 0},
	{Browser: 0},
	{kod: 0},
	{klava: 0},
	{load: 0},
	{Поворот: 0},
	{lod: 0},
	{AJAX: 0},
	{JSON: 0},
	{fon_urov: 0},
	{k_1: 0},
	{s_4: 0},
	{k_6: 0},
	{g_8: 0},
	{z_3: 0},
	{z_7: 0},
	{g_2: 0},
	{s_7: 0},
	{z_5: 0},
	{g_4: 0},
	{k_2: 0},
	{g_6: 0},
	{k_8: 0},
	{g_1: 0},
	{k_4: 0},
	{z_1: 0},
	{s_2: 0},
	{z_6: 0},
	{s_3: 0},
	{k_3: 0},
	{z_8: 0},
	{g_7: 0},
	{s_6: 0},
	{s_8: 0},
	{z_4: 0},
	{z_2: 0},
	{g_3: 0},
	{k_7: 0},
	{s_5: 0},
	{k_5: 0},
	{g_5: 0},
	{s_1: 0},
	{kybik: 0},
	{next: 0},
	{kryg: 0},
	{galka: 0},
	{Твинанимация: 0},
	{kartinki: 0},
	{zvyk: 0},
	{zekra: 0},
	{shet: 0},
	{demo: 0},
	{isDon: 0},
	{userSubscriptionStatus: 0},
	{API_RESPONSE: 0},
	{endpoint: 0},
	{checkSubscriptionStatus: 0}
];

self.InstanceType = {
	vakl: class extends self.ISpriteInstance {},
	vixod: class extends self.ISpriteInstance {},
	vkl: class extends self.ISpriteInstance {},
	vMenu: class extends self.ISpriteInstance {},
	kak_igrat: class extends self.ISpriteInstance {},
	naMenu: class extends self.ISpriteInstance {},
	naYroven_1: class extends self.ISpriteInstance {},
	predyprezdenie: class extends self.ISpriteInstance {},
	raz: class extends self.ISpriteInstance {},
	restrt: class extends self.ISpriteInstance {},
	sver: class extends self.ISpriteInstance {},
	fon_kakigrat: class extends self.ISpriteInstance {},
	fon_menu: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	audio: class extends self.IInstance {},
	obYsroistve: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	kod: class extends self.ISpriteInstance {},
	klava: class extends self.IInstance {},
	load: class extends self.ISpriteInstance {},
	lod: class extends self.ISpriteInstance {},
	AJAX: class extends self.IInstance {},
	JSON: class extends self.IJSONInstance {},
	fon_urov: class extends self.ISpriteInstance {},
	k_1: class extends self.ISpriteInstance {},
	s_4: class extends self.ISpriteInstance {},
	k_6: class extends self.ISpriteInstance {},
	g_8: class extends self.ISpriteInstance {},
	z_3: class extends self.ISpriteInstance {},
	z_7: class extends self.ISpriteInstance {},
	g_2: class extends self.ISpriteInstance {},
	s_7: class extends self.ISpriteInstance {},
	z_5: class extends self.ISpriteInstance {},
	g_4: class extends self.ISpriteInstance {},
	k_2: class extends self.ISpriteInstance {},
	g_6: class extends self.ISpriteInstance {},
	k_8: class extends self.ISpriteInstance {},
	g_1: class extends self.ISpriteInstance {},
	k_4: class extends self.ISpriteInstance {},
	z_1: class extends self.ISpriteInstance {},
	s_2: class extends self.ISpriteInstance {},
	z_6: class extends self.ISpriteInstance {},
	s_3: class extends self.ISpriteInstance {},
	k_3: class extends self.ISpriteInstance {},
	z_8: class extends self.ISpriteInstance {},
	g_7: class extends self.ISpriteInstance {},
	s_6: class extends self.ISpriteInstance {},
	s_8: class extends self.ISpriteInstance {},
	z_4: class extends self.ISpriteInstance {},
	z_2: class extends self.ISpriteInstance {},
	g_3: class extends self.ISpriteInstance {},
	k_7: class extends self.ISpriteInstance {},
	s_5: class extends self.ISpriteInstance {},
	k_5: class extends self.ISpriteInstance {},
	g_5: class extends self.ISpriteInstance {},
	s_1: class extends self.ISpriteInstance {},
	kybik: class extends self.ISpriteInstance {},
	next: class extends self.ISpriteInstance {},
	kryg: class extends self.ISpriteInstance {},
	galka: class extends self.ISpriteInstance {},
	kartinki: class extends self.ISpriteInstance {}
}