const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Plugins.PlatformInfo,
		C3.Behaviors.Tween,
		C3.Behaviors.Rotate,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Browser.Acts.GoBack,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.PlatformInfo.Cnds.IsOnAndroid,
		C3.Plugins.Browser.Cnds.IsPortraitLandscape,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.Destroy
	];
};
self.C3_JsPropNameTable = [
	{ur1: 0},
	{ur2: 0},
	{ur3: 0},
	{fonM: 0},
	{vMenu: 0},
	{vixod: 0},
	{v_menu: 0},
	{raz: 0},
	{sver: 0},
	{Touch: 0},
	{Browser: 0},
	{audio: 0},
	{obYsroistve: 0},
	{predyprezdenie: 0},
	{vkl: 0},
	{vakl: 0},
	{zvyki: 0},
	{Твинанимация: 0},
	{miska: 0},
	{prosto_logoped: 0},
	{load: 0},
	{Поворот: 0},
	{lod: 0},
	{restsrt: 0},
	{uroven_1: 0},
	{krest_1: 0},
	{obvod_1: 0},
	{krest_2: 0},
	{krest_3: 0},
	{krest_4: 0},
	{krest_5: 0},
	{krest_6: 0},
	{krest_7: 0},
	{krest_8: 0},
	{krest_9: 0},
	{krest_10: 0},
	{krest_11: 0},
	{obvod_2: 0},
	{obvod_3: 0},
	{obvod_4: 0},
	{obvod_5: 0},
	{obvod_6: 0},
	{obvod_7: 0},
	{obvod_8: 0},
	{obvod_9: 0},
	{obvod_10: 0},
	{obvod_11: 0},
	{krest: 0},
	{zekran: 0},
	{pobeda: 0},
	{zvyk: 0}
];

self.InstanceType = {
	ur1: class extends self.ISpriteInstance {},
	ur2: class extends self.ISpriteInstance {},
	ur3: class extends self.ISpriteInstance {},
	fonM: class extends self.ISpriteInstance {},
	vMenu: class extends self.ISpriteInstance {},
	vixod: class extends self.ISpriteInstance {},
	v_menu: class extends self.ISpriteInstance {},
	raz: class extends self.ISpriteInstance {},
	sver: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	audio: class extends self.IInstance {},
	obYsroistve: class extends self.IInstance {},
	predyprezdenie: class extends self.ISpriteInstance {},
	vkl: class extends self.ISpriteInstance {},
	vakl: class extends self.ISpriteInstance {},
	zvyki: class extends self.ISpriteInstance {},
	miska: class extends self.ISpriteInstance {},
	prosto_logoped: class extends self.ISpriteInstance {},
	load: class extends self.ISpriteInstance {},
	lod: class extends self.ISpriteInstance {},
	restsrt: class extends self.ISpriteInstance {},
	uroven_1: class extends self.ISpriteInstance {},
	krest_1: class extends self.ISpriteInstance {},
	obvod_1: class extends self.ISpriteInstance {},
	krest_2: class extends self.ISpriteInstance {},
	krest_3: class extends self.ISpriteInstance {},
	krest_4: class extends self.ISpriteInstance {},
	krest_5: class extends self.ISpriteInstance {},
	krest_6: class extends self.ISpriteInstance {},
	krest_7: class extends self.ISpriteInstance {},
	krest_8: class extends self.ISpriteInstance {},
	krest_9: class extends self.ISpriteInstance {},
	krest_10: class extends self.ISpriteInstance {},
	krest_11: class extends self.ISpriteInstance {},
	obvod_2: class extends self.ISpriteInstance {},
	obvod_3: class extends self.ISpriteInstance {},
	obvod_4: class extends self.ISpriteInstance {},
	obvod_5: class extends self.ISpriteInstance {},
	obvod_6: class extends self.ISpriteInstance {},
	obvod_7: class extends self.ISpriteInstance {},
	obvod_8: class extends self.ISpriteInstance {},
	obvod_9: class extends self.ISpriteInstance {},
	obvod_10: class extends self.ISpriteInstance {},
	obvod_11: class extends self.ISpriteInstance {},
	krest: class extends self.ISpriteInstance {}
}